version: "3"

services:
  ipfs:
    image: ipfs/go-ipfs
    container_name: ipfs_host
    tty: true
    privileged: true
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    command: daemon --migrate=true --enable-pubsub-experiment

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: worker
    privileged: true
    environment:
      - "IPFS_ADDR=$IPFS_ADDR"
      - "EMAIL=$EMAIL"
      - "NAME=$NAME"
      - "GRID_MODE=$GRID_MODE"
    tty: true
    volumes:
      - "$PWD:/workdir" 
    command: python3 ipfs_grid_worker_daemon.py

  notebook:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: notebook
    privileged: true
    tty: true
    environment:
      - "IPFS_ADDR=$IPFS_ADDR"
      - "EMAIL=$EMAIL"
      - "NAME=$NAME"
      - "GRID_MODE=$GRID_MODE"
    volumes:
      - "$PWD:/workdir"
    ports:
      - "8888:8888"
