version: "2"

services:
  ipfs:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.ipfs
    container_name: ipfs_host
    tty: true
    privileged: true
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"

  worker:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.worker
      args:
        email: 'clement.thorey@gmail.com'
        name: 'cthorey'
    container_name: worker
    privileged: true
    extra_hosts:
      - "host_name:35.205.35.110"
    volumes:
      - "$PWD:/workdir"
    tty: true
    command: python3 ipfs_grid_worker_daemon.py --compute
    depends_on:
      - ipfs

  notebook:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.worker
    container_name: notebook
    privileged: true
    tty: true
    extra_hosts:
      - "host_name:35.205.35.110"
    volumes:
      - "$PWD:/workdir"
    ports:
      - "8888:8888"
