version: "2"

services:
  ipfs:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.ipfs
    container_name: ipfs_host
    privileged: true
    tty: true
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"

  worker:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.worker-gpu
      args:
        email: 'openmined@openmined.com'
        name: 'openmined'
    container_name: worker
    privileged: true
    tty: true
    extra_hosts:
      - "host_name:$HOST_IP"
    devices:
      - /dev/nvidia0
    volumes:
      - "$PWD:/workdir"
    command: python3 ipfs_grid_worker_daemon.py --compute
    depends_on:
      - ipfs

  notebook:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.worker-gpu
    container_name: notebook
    privileged: true
    tty: true
    extra_hosts:
      - "host_name:$HOST_IP"
    devices:
      - /dev/nvidia0
    volumes:
      - "$PWD:/workdir"
    ports:
      - "8888:8888"
